version: '3'
services:
  mitm:
    build:
      context: ./mitm1
      dockerfile: dockerfile
    networks:
      test:      
        ipv4_address: 172.20.0.2
    tty: true         
  
  server:
    image: ishu06/srv1:apa
    networks:
      test:
        ipv4_address: 172.20.0.4
    tty: true
    
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    networks:
      test:
        ipv4_address: 172.20.0.3
    tty: true
    
networks:
  test:
    driver: bridge 
    ipam:      
      driver: default
      config: 
        - subnet: 172.20.0.0/16
