FROM  ubuntu:18.04
ENV LANG=en_US.UTF-8
ENV LC_ALL=C
RUN apt-get update

RUN export LC_ALL=C
RUN apt-get install -y git python3-dev python3-pip libffi-dev libssl-dev mlocate
RUN pip3 install netlib
RUN pip3 install mitmproxy

RUN mkdir -p "/home/mitmproxy/.mitmproxy"
WORKDIR = "/home/mitmproxy/.mitmproxy"
CMD ["/usr/local/bin/mitmdump"]
